### ISSUE TITLE
Install pgtt on windows server?

### ISSUE THREAD

**Issue by rgonzalezVeolia** [darold/pgtt#40] opened 2024-03-04 20:00 UTC
Hello, I have tried to install pgtt extension in postgres 13 on windows server, but I only receive errors when trying to run make... will anyone have any documents to install on windows?

**Comment by darold** [comment] 2024-03-05 04:45
I don't have enough knowledge and especially the desire to spend time on a port for Windows. If anyone can support this porting to Windows OS, a patch would be welcome. Thanks.

**Comment by rjuju** [comment] 2024-04-16 02:32
I compiled the latest version of pgtt for pg13 windows on windows.  Can you try the attached archive?  I also have an installer but unfortunately github doesn't allow linking it here. 

[pgtt-3.2.0-pg13-x64.zip](https://github.com/darold/pgtt/files/14986167/pgtt-3.2.0-pg13-x64.zip)

**Comment by rgonzalezVeolia** [comment] 2024-04-16 12:52
> I compiled the latest version of pgtt for pg13 windows on windows. Can you try the attached archive? I also have an installer but unfortunately github doesn't allow linking it here.
> 
> [pgtt-3.2.0-pg13-x64.zip](https://github.com/darold/pgtt/files/14986167/pgtt-3.2.0-pg13-x64.zip)

Thanks a lot!!! maybe can you send to me? rodrigo-andres.gonzalez@veolia.com

**Comment by rjuju** [comment] 2024-04-16 13:54
I tried but my email provider also blocks `.exe` attachments.  I uploaded it at https://transfert.free.fr/9dePGmw, the link should stay valid for the next 7 days.

**Comment by rgonzalezVeolia** [comment] 2024-04-16 13:59
> I tried but my email provider also blocks `.exe` attachments. I uploaded it at https://transfert.free.fr/9dePGmw, the link should stay valid for the next 7 days.

Thanks!!! Work fine on release 13... one question more, i tried to use in release 12, but this show me an incompatible version error. If possible use in release 12, what i must change?

**Comment by rjuju** [comment] 2024-04-16 14:20
Thank for the confirmation, that's a very good news!

> one question more, i tried to use in release 12, but this show me an incompatible version error. If possible use in release 12, what i must change?

That's expected.  While pgtt source code with compatible with pg12 up to the current development version of postgres (pg17), the compiled version is only compatible with a single major version.  That's why the installer hints you to install the extension in the postgres 13 directory (at least if it finds the correct registry keys).

I had to patch some stuff to be able to compile it and generate the installer, so I wanted to make sure that it was actually working before spending too much effort with this approach.  Now that I know it works I will work with @darold to make a few adjustments, and also fix the windows compile system.  Once done I will be able to generate an installer for all supported version and will give them to @darold so he can upload them on the release page.

**Comment by rgonzalezVeolia** [comment] 2024-04-16 14:25
thanks for your help!!! i'll be waiting!!!

**Comment by rjuju** [comment] 2024-04-21 02:42
I finally had time to work on this.  I just sent a PR to ease the windows installer creation (the script also needed some changes) and using those I could generate installers for all supported postgre smajor versions (12 to 16).  I uploaded them at https://transfert.free.fr/D8M2FtD

If you can test the pg12 version that would confirm that it's all good and that we can publish them on the release apge.

**Comment by rgonzalezVeolia** [comment] 2024-04-22 14:02
Thanks!!!
pgtt installed OK. But, the tables exist while the session exist. This tables must be registered under pgtt_schema?

**Comment by rjuju** [comment] 2024-04-23 02:30
I realized that the new version is not the "real" 3.2.0" but the latest commit, which includes some other changes related to the LOAD 'pgtt' thing.

Was the installer for version 13 actually working?  If yes I can try to generate the installer for version 12 with the "real" pgtt version 3.2.0 and see if that fixes the problem.  In that case we will be able to look at this issue before releasing a new pgtt version.

**Comment by rgonzalezVeolia** [comment] 2024-04-23 13:17
> I realized that the new version is not the "real" 3.2.0" but the latest commit, which includes some other changes related to the LOAD 'pgtt' thing.
> 
> Was the installer for version 13 actually working? If yes I can try to generate the installer for version 12 with the "real" pgtt version 3.2.0 and see if that fixes the problem. In that case we will be able to look at this issue before releasing a new pgtt version.

Not really. The installer work, i can create the extension and load, but the temporary tables is not working, i mean, this exist only in the session, then this tables desapear. This tables, must stay in the pgtt_schema, and is not stayed there.

**Comment by rgonzalezVeolia** [comment] 2024-04-23 13:48
![image](https://github.com/darold/pgtt/assets/162188882/85431c32-9b6d-4d90-b14b-921206c5ae33)

**Comment by rjuju** [comment] 2024-04-23 14:11
so the same behaviour with both the first installer and the new one?

just to be sure, did you check with CREATE GLOBAL TEMPORARY TABLE rather that with GLOBAL between comments?

**Comment by rgonzalezVeolia** [comment] 2024-04-23 14:15
> so the same behaviour with both the first installer and the new one?
Yes, same behavior.
> just to be sure, did you check with CREATE GLOBAL TEMPORARY TABLE rather that with GLOBAL between comments?
Yes, same behavior, and show me a warning of obsolete.

**Comment by rgonzalezVeolia** [comment] 2024-04-23 14:16
![image](https://github.com/darold/pgtt/assets/162188882/e24347b9-303a-4f52-9af0-6b19dd6dfadc)

**Comment by dariocorti** [comment] 2024-05-24 15:27
Hi, I need the latest version of the extension for Windows and compatible with PostgreSQL 16, is there any update here?

**Comment by darold** [comment] 2024-05-24 15:45
Hi @dariocorti, have you tested latest development code? If so, do you have the same issue above?

**Comment by dariocorti** [comment] 2024-05-25 06:11
> Hi @dariocorti, have you tested latest development code? If so, do you have the same issue above?

Hi @darold, I tried to compile the last versione with Microsoft Visual studio to generate del .dll file, but when I execute the LOAD command in Postgres I recevie the errore that it's not compatible with 16 version. Is there a package already compiled ad .dll that working?

**Comment by darold** [comment] 2024-05-25 06:26
How about if you enable the extension by setting `session_preload_libraries='pgtt'`?

**Comment by rjuju** [comment] 2024-05-25 06:37
You can find an installer and a zip file containing all the required files to install the latest commit of pgtt on pg16: https://transfert.free.fr/AOao3oi

As this is the latest commit, includes the recent changes to allow `session_preload_libraries='pgtt'` rather than an explicit `LOAD` command.

If you can confirm that this is fully functionnal is would be a very good news as we will be able to provide those for all pgtt versions on all pg versions.

**Comment by rjuju** [comment] 2024-05-26 08:20
@rgonzalezVeolia I have been unable to reproduce the issue on linux.  Just to be sure, did you refresh the pgad;im object tree **after** execute the `CREATE /* GLOBAL */ TEMPORARY TABLE` command?

Or maybe the problem you hit was actually something like what I describe in https://github.com/darold/pgtt/pull/48 ?  That would explain why it seems to fail but would actually be just a corner case bug.

**Comment by dariocorti** [comment] 2024-05-27 07:39
> You can find an installer and a zip file containing all the required files to install the latest commit of pgtt on pg16: https://transfert.free.fr/AOao3oi
> 
> As this is the latest commit, it includes the recent changes to allow `session_preload_libraries='pgtt'` rather than an explicit `LOAD` command.
> 
> If you can confirm that this is fully functionnal is would be a very good news as we will be able to provide those for all pgtt versions on all pg versions.

Hi @rjuju, I confirm that works!! Thanks!

**Comment by rgonzalezVeolia** [comment] 2024-05-27 13:03
> @rgonzalezVeolia I have been unable to reproduce the issue on linux. Just to be sure, did you refresh the pgad;im object tree **after** execute the `CREATE /* GLOBAL */ TEMPORARY TABLE` command?
> 
> Or maybe the problem you hit was actually something like what I describe in #48 ? That would explain why it seems to fail but would actually be just a corner case bug.

Yes, refresh after execution ...

**Comment by rgonzalezVeolia** [comment] 2024-05-27 13:50
![image](https://github.com/darold/pgtt/assets/162188882/17e20d56-8e63-4422-bce8-4a368b97aa49)

**Comment by rgonzalezVeolia** [comment] 2024-05-27 13:51
You can see that i create temporary table. But, is not in the list from pgtt_schema.

**Comment by rjuju** [comment] 2024-05-27 14:00
You need to do the same `LOAD 'pgtt';` in the new connection, and issue another query first to avoid the bug that was fiexed yesterday, so something like

```sql
LOAD 'pgtt';
SELECT 1;
SELECT * FROM hr_attributetypemodel;
```

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:02
![image](https://github.com/darold/pgtt/assets/162188882/a83a126b-9ad3-4476-9e4c-d2aeec6d2f7d)

**Comment by rjuju** [comment] 2024-05-27 14:06
that's really strange.  Can you show the result of `SHOW search_path;`?  It should at least confirm that the extension seems to be setup as intended.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:07
![image](https://github.com/darold/pgtt/assets/162188882/3cf5866d-374c-49b6-9e61-8dcf51d1dd98)

**Comment by rjuju** [comment] 2024-05-27 14:07
ah, then it's NOT working at all.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:08
![image](https://github.com/darold/pgtt/assets/162188882/df5b650c-d569-43c3-8960-76749eeb495f)

**Comment by rjuju** [comment] 2024-05-27 14:09
do you have other extension installed?  what does `SHOW shared_preload_libraries;` output?

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:10
![image](https://github.com/darold/pgtt/assets/162188882/5f9af8e7-f349-4f96-970e-2c6ca7eadd62)

**Comment by rjuju** [comment] 2024-05-27 14:11
How about `SHOW pgtt.enabled;` ?

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:13
![image](https://github.com/darold/pgtt/assets/162188882/902b1301-293e-442c-9598-f96e71b1f627)
not recognized.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:16
![image](https://github.com/darold/pgtt/assets/162188882/bb0b01d8-168c-4b5e-88f3-ceab0a2a69ec)

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:18
how can i deinstall pgtt?, to try install again, y then do i will test.

**Comment by darold** [comment] 2024-05-27 14:20
How about the output if you do the following:
```
SET pggtt.enabled TO on;
LOAD 'pgtt';
SELECT * FROM pgtt_schema.pg_global_temp_tables;
SELECT * FROM hr_attributetypemodel;
```

**Comment by rjuju** [comment] 2024-05-27 14:21
you should remove the pgtt.dll that's in one of the sub directories of that installation (in C:\Program Files or similar typically)

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:22
![image](https://github.com/darold/pgtt/assets/162188882/29082d0f-0660-4e39-802b-17daca9687e1)

**Comment by darold** [comment] 2024-05-27 14:23
it can't works, the table have not been created.

**Comment by darold** [comment] 2024-05-27 14:25
Let's restart from the table creation
```
SET pggtt.enabled TO on;
LOAD 'pgtt';
CREATE GLOBAL TEMPORARY TABLE hr_attributetypemodel (id int);
SELECT * FROM pgtt_schema.pg_global_temp_tables;
\c - -
SET pggtt.enabled TO on;
LOAD 'pgtt';
SELECT * FROM pgtt_schema.pg_global_temp_tables;
SELECT * FROM hr_attributetypemodel;
```

**Comment by darold** [comment] 2024-05-27 14:33
can you execute exactly the script I have post please just to be sure that it doesn't work in this simple use. Just copy paste the code in psql.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:36
SET pggtt.enabled TO on;   (this line is ok?)

**Comment by rjuju** [comment] 2024-05-27 14:41
And if needed here's an installer for the latest commit (f84fa01e57e9cd2085fa6feb96a956c7ab3e0cdd) for pg13 https://transfert.free.fr/c3PHn7Z

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:44
![image](https://github.com/darold/pgtt/assets/162188882/d8f9a0a0-4e31-43c6-933d-039faa2fc937)

**Comment by darold** [comment] 2024-05-27 14:49
It behave just like if the extension is not loaded. I guess that if you execute the following
```
SET pggtt.enabled TO on;
LOAD 'pgtt';
SELECT 1;
SHOW search_path;
CREATE GLOBAL TEMPORARY TABLE hr_attributetypemodel (id int);
\d hr_attributetypemodel
```
it will not change the search_path and create a real temporary table that of course disappears when we reconnect.

**Comment by darold** [comment] 2024-05-27 14:50
if you can remove the extension and use latest installer send by rjuju and give it a try.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 14:51
> SET pggtt.enabled TO on;
> LOAD 'pgtt';
> SELECT 1;
> SHOW search_path;
> CREATE GLOBAL TEMPORARY TABLE hr_attributetypemodel (id int);
> \d hr_attributetypemodel

![image](https://github.com/darold/pgtt/assets/162188882/856451b5-2d9c-4c17-a0c3-1543828b7f3a)

**Comment by darold** [comment] 2024-05-27 14:56
I'm dry of solution here, next test could be to use PG16 like @dariocorti and see if you still have the issue.

**Comment by darold** [comment] 2024-05-27 14:57
There is nothing in the log file that could be of any interest to find why the extension not loaded?

**Comment by rgonzalezVeolia** [comment] 2024-05-27 15:02
> SET pggtt.enabled TO on;
> LOAD 'pgtt';
> SELECT 1;
> SHOW search_path;
> CREATE GLOBAL TEMPORARY TABLE hr_attributetypemodel (id int);
> \d hr_attributetypemodel

![image](https://github.com/darold/pgtt/assets/162188882/a4fbfc2b-ca60-4b9e-ae4f-4b185bd53539)

**Comment by rgonzalezVeolia** [comment] 2024-05-27 15:03
> if you can remove the extension and use latest installer send by rjuju and give it a try.

did it. Same problem.

**Comment by darold** [comment] 2024-05-27 15:08
Well give a try with PG16 that's all I can say now.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 15:11
OK, Im installing on my machine, not same server with problem. I'll let you know how it work.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 16:05
![image](https://github.com/darold/pgtt/assets/162188882/6a5aa98f-d226-4b63-9c39-6f22f4e9a836)

**Comment by rgonzalezVeolia** [comment] 2024-05-27 16:06
Version 16.

**Comment by darold** [comment] 2024-05-27 16:14
So this is a problem with PG13, thanks for the test.

**Comment by rgonzalezVeolia** [comment] 2024-05-27 16:29
would you try repair  to PG13?

**Comment by darold** [comment] 2024-05-27 18:18
I will let @rjuju answer to this question but why are you using pgtt? If this is for a migration for Oracle I recommend you to use  PG16. Why do you need PG13?

**Comment by rgonzalezVeolia** [comment] 2024-05-27 18:19
PG13 is a requirement from custom. :|

**Comment by darold** [comment] 2024-05-27 18:22
And why using Global Temporary Table? Also note that pgtt works perfectly on PG13 under Linux, does Windows is also a customer requirement?

**Comment by rgonzalezVeolia** [comment] 2024-05-27 18:23
yes, is requirement also.

**Comment by rjuju** [comment] 2024-05-28 02:40
I tried locally on a pg16 server I could manage to create, using the last zip file I shared above:

```sql
postgres=# select version();
                          version
------------------------------------------------------------
 PostgreSQL 16.1, compiled by Visual C++ build 1937, 64-bit
(1 row)

postgres=# show search_path;
   search_path
-----------------
 "$user", public
(1 row)

postgres=# load 'pgtt';
LOAD
postgres=# show search_path;
    search_path
--------------------
 public,pgtt_schema
(1 row)


postgres=# create global temporary table t_tbl(id integer);
WARNING:  GLOBAL is deprecated in temporary table creation
LINE 1: create global temporary table t_tbl(id integer);
               ^
CREATE TABLE
postgres=# \c
You are now connected to database "postgres" as user "postgres".
postgres=# load 'pgtt';
LOAD

postgres=# select * from t_tbl;
 id
----
(0 rows)
```

It works as expected.  I really have no explanation why it doesn't work for you.

**Comment by rjuju** [comment] 2024-05-28 04:02
sorry I missed that you confirmed that it's working for you for pg16.

I try to do the same on a local pg13 and I confirm that I have the same behaviour as you: nothing works. I added an explicit WARNING message at the beginning of the LOAD command and it's also not emitted, so it's clear that pg13 on windows for some reason is broken. since it works just fine on Linux, your best hope is to contact edb packagers and ask them what needs to be done to make it work, as it's the only moving piece here.

**Comment by darold** [comment] 2024-05-31 02:31
I'm closing this issue, port to Windows is considered as done. Thanks again to @rjuju

**Comment by rjuju** [comment] 2024-05-31 06:57
@rgonzalezVeolia  good news, I finally found why the extension wasn't working on versions lower than 16.  This is now fixed and I uploaded freshly built installers.  You can download them from the version 4 release page at https://github.com/darold/pgtt/releases/tag/v4.0.

A confirmation that this is also working for you would be great.

**Comment by rgonzalezVeolia** [comment] 2024-05-31 13:36
Great!!!
![image](https://github.com/darold/pgtt/assets/162188882/2015f709-5004-4714-9a58-e5de4cc6bd2a)

![image](https://github.com/darold/pgtt/assets/162188882/a8f0f4c6-1314-49ab-93b6-c8f000e271dc)

Work!!!

**Comment by rjuju** [comment] 2024-05-31 14:18
Excellent news, thanks a lot for checking!

I can now finally close the issue as resolved :)

**Closed** 2024-06-06 13:18 UTC

**Comment by rjuju** [comment] 2025-10-03 23:37
hi @vrnvorona

unfortunately starting with pg17, postgres switched the toolchain on windows to meson and one direct consequence is that the only method I knew about on how to compile postgres extensions on Windows doesn't work anymore.

as I'm not a Windows user I don't know how to fix that problem, so unless someone shows up with some details instructions on how to build extensions with meson there won't be new windows installers for pg17 and above.
