### ISSUE TITLE
PostgreSQL 16 support

### ISSUE THREAD

**Issue by devrimgunduz** [darold/pgtt#33] opened 2023-09-11 11:48 UTC
Hi,

2.10 fails to build against PostgreSQL 16, which is due this Thursday. Can you please take a look? Errors are below.

Thanks!

Regards, Devrim

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -I/usr/pgsql-16/include -Wno-uninitialized -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgtt.bc pgtt.c
pgtt.c:143:12: error: static declaration of 'get_extension_schema' follows non-static declaration
  143 | static Oid get_extension_schema(Oid ext_oid);
      |            ^~~~~~~~~~~~~~~~~~~~
In file included from pgtt.c:36:
/usr/pgsql-16/include/server/commands/extension.h:50:17: note: previous declaration of 'get_extension_schema' with type 'Oid(Oid)' {aka 'unsigned int(unsigned int)'}
   50 | extern Oid      get_extension_schema(Oid ext_oid);
      |                 ^~~~~~~~~~~~~~~~~~~~
pgtt.c: In function 'GttHashTableDeleteAll':
pgtt.c:180:21: warning: declaration of 'hentry' shadows a previous local [-Wshadow=compatible-local]
  180 |         GttHashEnt *hentry; \
      |                     ^~~~~~
pgtt.c:1337:17: note: in expansion of macro 'GttHashTableDelete'
 1337 |                 GttHashTableDelete(hentry->name);
      |                 ^~~~~~~~~~~~~~~~~~
pgtt.c:1326:21: note: shadowed declaration is here
 1326 |         GttHashEnt *hentry = NULL;
      |                     ^~~~~~
pgtt.c: In function 'create_temporary_table_internal':
pgtt.c:1571:25: error: too few arguments to function 'DefineIndex'
 1571 |                         DefineIndex(relid,      /* OID of heap relation */
      |                         ^~~~~~~~~~~
In file included from pgtt.c:35:
/usr/pgsql-16/include/server/commands/defrem.h:27:22: note: declared here
   27 | extern ObjectAddress DefineIndex(Oid relationId,
      |                      ^~~~~~~~~~~
make[1]: *** [<builtin>: pgtt.o] Error 1
make[1]: *** Waiting for unfinished jobs....
pgtt.c:143:12: error: static declaration of 'get_extension_schema' follows non-static declaration
static Oid get_extension_schema(Oid ext_oid);
           ^
/usr/pgsql-16/include/server/commands/extension.h:50:12: note: previous declaration is here
extern Oid      get_extension_schema(Oid ext_oid);
                ^
pgtt.c:1584:12: error: too few arguments to function call, expected 11, have 10
                                                false); /* quiet */
                                                     ^
/usr/pgsql-16/include/server/commands/defrem.h:27:22: note: 'DefineIndex' declared here
extern ObjectAddress DefineIndex(Oid relationId,
                     ^
pgtt.c:1859:1: error: static declaration of 'get_extension_schema' follows non-static declaration
get_extension_schema(Oid ext_oid)
^
/usr/pgsql-16/include/server/commands/extension.h:50:12: note: previous declaration is here
extern Oid      get_extension_schema(Oid ext_oid);
                ^

**Comment by devrimgunduz** [comment] 2023-09-13 22:10
ping

**Comment by darold** [comment] 2023-09-14 04:19
Hi @devrimgunduz, got it but not able to reproduce with gcc. I will give a try with clang. Anyway there is another compatibility issue with PG16, the regexp compilation is failing and regression test are broken. Working on this first. I will let you know when all will be fixed an a new version released.

**Comment by darold** [comment] 2023-09-17 14:15
Hi Devrim,

I was not able to reproduce this error but I've tried to fix it, all others pending issues have been fixed too . Can you please try to compile latest development code and tell me if this is solved? Also note that new version will remove support to PG version prior 12.

Thanks

**Comment by devrimgunduz** [comment] 2023-09-17 19:23
Hi @darold ,

Build is crystal clear now. Thanks!

Let me know when you release the new version.

Regards, Devrim

**Comment by darold** [comment] 2023-09-17 20:50
Thanks for the feedback Devrim, new release v3.0 has been published.

**Closed by darold** 2023-09-17 20:50 UTC
